//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/Controller.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @Controller: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @Controller()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""Controller"",
    ""maps"": [
        {
            ""name"": ""LAND"",
            ""id"": ""0d280664-e35a-4520-9ab0-b94cf2c2ff0b"",
            ""actions"": [
                {
                    ""name"": ""MOVEH"",
                    ""type"": ""Value"",
                    ""id"": ""c6bb8ecd-e53b-4138-9bbd-c1f6bee0de0e"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""MOVEV"",
                    ""type"": ""Value"",
                    ""id"": ""820da1ca-eeb2-49ec-97a2-d5cfb2902ce0"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""JUMP"",
                    ""type"": ""Button"",
                    ""id"": ""074f1c53-ea4a-4f0f-ad48-5d7f04de9362"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""GRAB"",
                    ""type"": ""Button"",
                    ""id"": ""ea1e952e-be62-48cb-94a3-2eb27b08dd57"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""AIM"",
                    ""type"": ""Value"",
                    ""id"": ""06094fc3-a728-4de6-81ce-5599eae51248"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""BACK"",
                    ""type"": ""Button"",
                    ""id"": ""1e225a6b-2573-4803-a800-f5495d96f00a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""AD"",
                    ""id"": ""59dd6619-c4d8-42cd-aa64-35ea0b056ceb"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MOVEH"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""a6795858-9f2c-42d7-89d5-7f2f6a3ea37c"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MOVEH"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""75d4dd8e-961f-4dab-bed7-f8d7180d030e"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MOVEH"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""QD"",
                    ""id"": ""b5e3e7ec-bf74-4dca-aefd-27218c223401"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MOVEH"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""aa97c214-a722-4140-adbb-c23f6872bd95"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MOVEH"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""d9db7d63-677b-4845-acb8-d5f20026ed57"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MOVEH"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""GAMEPAD"",
                    ""id"": ""10c0434b-2924-4577-9fc9-bc3acae04d2d"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MOVEH"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""95542719-9f87-40d8-a305-25830f9ffb9d"",
                    ""path"": ""<Gamepad>/leftStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MOVEH"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""690781d4-3689-48cb-90b2-ce8919fc0e66"",
                    ""path"": ""<Gamepad>/leftStick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MOVEH"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""97eada6c-2c4f-46a4-a48c-4ecff31de6d7"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""JUMP"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""16d3398b-1e37-43cf-99db-6a6a35697cc2"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""JUMP"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b2ccc430-e03d-42a2-8859-106d048df1ed"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""GRAB"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4e4fe697-b48c-4ac5-b902-12c2b8e26f99"",
                    ""path"": ""<Gamepad>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""GRAB"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""94b86222-21e3-4949-8501-3d13c6f33698"",
                    ""path"": ""2DVector(mode=2)"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""AIM"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""02ee9b69-144b-4c61-b58b-1923b33f2e16"",
                    ""path"": ""<Gamepad>/rightStick/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""AIM"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""45583b6b-db44-4946-ab32-f608a0e92149"",
                    ""path"": ""<Gamepad>/rightStick/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""AIM"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""f86a4d78-579b-4340-a8eb-1bfe6c9aaeec"",
                    ""path"": ""<Gamepad>/rightStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""AIM"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""fbb0de69-4ccc-4343-b5aa-64fe73589ab9"",
                    ""path"": ""<Gamepad>/rightStick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""AIM"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""WS"",
                    ""id"": ""aef00640-c28a-41ba-bf92-8d8e63fbb718"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MOVEV"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""802a0ba0-d4b7-4b0d-be7e-f99fafa0707a"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MOVEV"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""7925ca58-b297-49b7-a5ef-ba561cbef17d"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MOVEV"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""ZS"",
                    ""id"": ""41b72c0b-8f15-4204-8607-2b042ca9c912"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MOVEV"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""e46a0c64-5e9f-42c8-9de0-f60addf15306"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MOVEV"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""ade0455f-a071-45a9-ace7-57899453e5d0"",
                    ""path"": ""<Keyboard>/z"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MOVEV"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""GAMEPAD"",
                    ""id"": ""9adfa1a8-9f15-4e59-800d-199c644cc86e"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MOVEV"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""8cbeeb97-b845-45cb-a82f-fbb521267e48"",
                    ""path"": ""<Gamepad>/leftStick/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MOVEV"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""6a747689-60d5-4d66-b7cc-b1c9e6bbad19"",
                    ""path"": ""<Gamepad>/leftStick/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MOVEV"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""1ffde486-25ad-45f3-9860-9455ee2a3ca3"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""BACK"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""WALL"",
            ""id"": ""002b5fcb-2601-4f3c-b052-5fd157f2516c"",
            ""actions"": [],
            ""bindings"": []
        }
    ],
    ""controlSchemes"": []
}");
        // LAND
        m_LAND = asset.FindActionMap("LAND", throwIfNotFound: true);
        m_LAND_MOVEH = m_LAND.FindAction("MOVEH", throwIfNotFound: true);
        m_LAND_MOVEV = m_LAND.FindAction("MOVEV", throwIfNotFound: true);
        m_LAND_JUMP = m_LAND.FindAction("JUMP", throwIfNotFound: true);
        m_LAND_GRAB = m_LAND.FindAction("GRAB", throwIfNotFound: true);
        m_LAND_AIM = m_LAND.FindAction("AIM", throwIfNotFound: true);
        m_LAND_BACK = m_LAND.FindAction("BACK", throwIfNotFound: true);
        // WALL
        m_WALL = asset.FindActionMap("WALL", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // LAND
    private readonly InputActionMap m_LAND;
    private List<ILANDActions> m_LANDActionsCallbackInterfaces = new List<ILANDActions>();
    private readonly InputAction m_LAND_MOVEH;
    private readonly InputAction m_LAND_MOVEV;
    private readonly InputAction m_LAND_JUMP;
    private readonly InputAction m_LAND_GRAB;
    private readonly InputAction m_LAND_AIM;
    private readonly InputAction m_LAND_BACK;
    public struct LANDActions
    {
        private @Controller m_Wrapper;
        public LANDActions(@Controller wrapper) { m_Wrapper = wrapper; }
        public InputAction @MOVEH => m_Wrapper.m_LAND_MOVEH;
        public InputAction @MOVEV => m_Wrapper.m_LAND_MOVEV;
        public InputAction @JUMP => m_Wrapper.m_LAND_JUMP;
        public InputAction @GRAB => m_Wrapper.m_LAND_GRAB;
        public InputAction @AIM => m_Wrapper.m_LAND_AIM;
        public InputAction @BACK => m_Wrapper.m_LAND_BACK;
        public InputActionMap Get() { return m_Wrapper.m_LAND; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(LANDActions set) { return set.Get(); }
        public void AddCallbacks(ILANDActions instance)
        {
            if (instance == null || m_Wrapper.m_LANDActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_LANDActionsCallbackInterfaces.Add(instance);
            @MOVEH.started += instance.OnMOVEH;
            @MOVEH.performed += instance.OnMOVEH;
            @MOVEH.canceled += instance.OnMOVEH;
            @MOVEV.started += instance.OnMOVEV;
            @MOVEV.performed += instance.OnMOVEV;
            @MOVEV.canceled += instance.OnMOVEV;
            @JUMP.started += instance.OnJUMP;
            @JUMP.performed += instance.OnJUMP;
            @JUMP.canceled += instance.OnJUMP;
            @GRAB.started += instance.OnGRAB;
            @GRAB.performed += instance.OnGRAB;
            @GRAB.canceled += instance.OnGRAB;
            @AIM.started += instance.OnAIM;
            @AIM.performed += instance.OnAIM;
            @AIM.canceled += instance.OnAIM;
            @BACK.started += instance.OnBACK;
            @BACK.performed += instance.OnBACK;
            @BACK.canceled += instance.OnBACK;
        }

        private void UnregisterCallbacks(ILANDActions instance)
        {
            @MOVEH.started -= instance.OnMOVEH;
            @MOVEH.performed -= instance.OnMOVEH;
            @MOVEH.canceled -= instance.OnMOVEH;
            @MOVEV.started -= instance.OnMOVEV;
            @MOVEV.performed -= instance.OnMOVEV;
            @MOVEV.canceled -= instance.OnMOVEV;
            @JUMP.started -= instance.OnJUMP;
            @JUMP.performed -= instance.OnJUMP;
            @JUMP.canceled -= instance.OnJUMP;
            @GRAB.started -= instance.OnGRAB;
            @GRAB.performed -= instance.OnGRAB;
            @GRAB.canceled -= instance.OnGRAB;
            @AIM.started -= instance.OnAIM;
            @AIM.performed -= instance.OnAIM;
            @AIM.canceled -= instance.OnAIM;
            @BACK.started -= instance.OnBACK;
            @BACK.performed -= instance.OnBACK;
            @BACK.canceled -= instance.OnBACK;
        }

        public void RemoveCallbacks(ILANDActions instance)
        {
            if (m_Wrapper.m_LANDActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(ILANDActions instance)
        {
            foreach (var item in m_Wrapper.m_LANDActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_LANDActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public LANDActions @LAND => new LANDActions(this);

    // WALL
    private readonly InputActionMap m_WALL;
    private List<IWALLActions> m_WALLActionsCallbackInterfaces = new List<IWALLActions>();
    public struct WALLActions
    {
        private @Controller m_Wrapper;
        public WALLActions(@Controller wrapper) { m_Wrapper = wrapper; }
        public InputActionMap Get() { return m_Wrapper.m_WALL; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(WALLActions set) { return set.Get(); }
        public void AddCallbacks(IWALLActions instance)
        {
            if (instance == null || m_Wrapper.m_WALLActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_WALLActionsCallbackInterfaces.Add(instance);
        }

        private void UnregisterCallbacks(IWALLActions instance)
        {
        }

        public void RemoveCallbacks(IWALLActions instance)
        {
            if (m_Wrapper.m_WALLActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IWALLActions instance)
        {
            foreach (var item in m_Wrapper.m_WALLActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_WALLActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public WALLActions @WALL => new WALLActions(this);
    public interface ILANDActions
    {
        void OnMOVEH(InputAction.CallbackContext context);
        void OnMOVEV(InputAction.CallbackContext context);
        void OnJUMP(InputAction.CallbackContext context);
        void OnGRAB(InputAction.CallbackContext context);
        void OnAIM(InputAction.CallbackContext context);
        void OnBACK(InputAction.CallbackContext context);
    }
    public interface IWALLActions
    {
    }
}
